baseURL: "https://memo.mx"
title: Memo Garcia
# paginate: 5000 # Deprecated
theme: PaperMod

publishDir: .
themesDir: themes

enableGitInfo: true

googleAnalytics: "G-ZRB1GGCC9B"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Tools
          url: tools
          weight: 3
        - name: $DAYJOB
          url: dayjob
          weight: 4
        - name: Startup
          url: startup
          weight: 5
        - name: YouTube
          url: youtube
          weight: 6
        - name: Books
          url: books
          weight: 7
        - name: About
          url: about
          weight: 8
outputs:
  home:
    - HTML
    - RSS

params:
  env: production
  description: "Memo's personal blog"
  author: "Memo Garcia"

  defaultTheme: dark # Changed from auto to dark
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  homeInfoParams:
    Title: "いらしゃいませい"
    Content: >
      Software Engineer


      Master of Chaos


      Wizard lvl 9


      Human
  socialIcons:
    - name: mastodon
      url: "https://mastodon.social/@__warlord__"
    - name: RSS
      url: "index.xml"

  analytics:
    google:
      SiteVerificationTag: "G-ZRB1GGCC9B"

  assets:
    disableHLJS: true
    # Update theme colors to match cyberpunk palette
    theme_color: "#0d0221"
    msapplication_TileColor: "#0d0221"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
      hardWraps: false
  highlight:
    noClasses: true
    codeFences: true
    guessSyntax: true
    style: solarized-dark
    # anchorLineNos: true
    # lineNos: true

pagination:
  pagerSize: 5000

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter: {} # Was disableInlineCSS: true, which is deprecated in Hugo v0.141.0

ignoreLogs:
  - "err-youtube-remote"
