baseURL: "https://memo.mx"
title: Memo Garcia
paginate: 5000
theme: PaperMod

publishDir: .
themesDir: themes

enableGitInfo: true

googleAnalytics: "G-ZRB1GGCC9B"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: About
          url: about
          weight: 5
        # - name: Search
        #   url: search/
        #   weight: 10
        # - name: Tags
        #   url: tags/
        #   weight: 10
        # - name: CV
        #   url: https://github.com/memogarcia/cv
        - name: Continuous Learning
          url: https://memogarcia.gitbook.io/continuous-learning/
outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Memo's personal blog"
  author: "Memo Garcia"

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  # images: ["papermod-cover.png"]

  homeInfoParams:
    Title: "いらしゃいませい"
    Content: >
      Software Engineer


      Master of Chaos


      Wizard lvl 9


      Human
  socialIcons:
    - name: mastodon
      url: "https://mastodon.social/@__warlord__"
    - name: github
      url: "https://github.com/memogarcia"
    - name: gitlab
      url: "https://gitlab.com/memogarcia"
    - name: YouTube
      url: "https://www.youtube.com/@memo.i.garcia"
    - name: Discord
      url: "https://discord.com/channels/1014044476588707840/1014044477687595081"
    # - name: LinkedIn
    #   url: "https://www.linkedin.com/in/guillermo-ramirez-garcia"
    - name: RSS
      url: "index.xml"

  analytics:
    google:
      SiteVerificationTag: "G-ZRB1GGCC9B"

  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: true
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: solarized-dark
