baseURL: "https://memo.mx"
title: Memo Garcia
paginate: 5000
theme: PaperMod

publishDir: .
themesDir: themes

enableGitInfo: true

googleAnalytics: "G-ZRB1GGCC9B"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Understanding computer networks by analogy
          url: understanding-networks-by-analogy
          weight: 6
        - name: DevOps Life
          url: devops
          weight: 7
        - name: About
          url: about
          weight: 8
outputs:
  home:
    - HTML
    - RSS

params:
  env: production
  description: "Memo's personal blog"
  author: "Memo Garcia"

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  homeInfoParams:
    Title: "いらしゃいませい"
    Content: >
      Software Engineer


      Master of Chaos


      Wizard lvl 9


      Human
  socialIcons:
    - name: mastodon
      url: "https://mastodon.social/@__warlord__"
    - name: RSS
      url: "index.xml"

  analytics:
    google:
      SiteVerificationTag: "G-ZRB1GGCC9B"

  assets:
    disableHLJS: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
      hardWraps: false
  highlight:
    noClasses: true
    codeFences: true
    guessSyntax: true
    style: solarized-dark
    # anchorLineNos: true
    # lineNos: true

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true