baseURL = "https://memooo.ooo/"
languageCode = "en-us"
title = "Memo Garcia"
theme = "paper"

publishDir = "."

paginate = 300

enableRobotsTXT = true

[params]
    author = "Memo Garcia"
    github = "memogarcia"
    gitlab = "memogarcia"
    sitename = "Memo Garcia"

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'About'
  url = '/about/'
  weight = -110
