baseURL: "https://memo.mx"
title: Memo Garcia
theme: PaperMod

publishDir: .
themesDir: themes

enableGitInfo: true

# Analytics
googleAnalytics: "G-ZRB1GGCC9B"

# Features
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

# Performance
enableHTTPS: true
canonicalize: true
# relativeURLs: false
# refLinksNotFoundURL: "/404.html"

# SEO
enableSitemap: true
enableRSS: true

# Minification
minify:
  disableXML: true
  disableHTML: false
  disableCSS: false
  disableJS: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
    css:
      keepCSS2: true
    js:
      keepVarNames: false

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: Books
          url: books
          weight: 7
        - name: About
          url: about
          weight: 8
outputs:
  home:
    - HTML
    - RSS

# Taxonomies
taxonomies:
  category: categories
  tag: tags
  series: series


# Related Content
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70

params:
  env: production
  description: "Memo's personal blog"
  author: "Memo Garcia"
  keywords: ["software engineer", "devops", "cloud", "kubernetes", "python"]
  
  # SEO & Open Graph
  images: ["papermod-cover.png"]
  ogImage: "/papermod-cover.png"
  locale: en_US
  
  # Schema.org
  schema:
    publisherType: Person
    siteType: Blog
    
  # Security Headers (for Netlify/Vercel deployment)
  headers:
    X-Frame-Options: "SAMEORIGIN"
    X-Content-Type-Options: "nosniff"
    Referrer-Policy: "strict-origin-when-cross-origin"
    Permissions-Policy: "geolocation=(), microphone=(), camera=()"

  defaultTheme: dark # Changed from auto to dark
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: false
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false

  # Favicon
  favicon: "/favicon.ico"
  favicon16x16: "/favicon-16x16.png"
  favicon32x32: "/favicon-32x32.png"
  apple_touch_icon: "/apple-touch-icon.png"
  safari_pinned_tab: "/safari-pinned-tab.svg"
  
  homeInfoParams:
    Title: "いらしゃいませい"
    Content: >
      Software Engineer


      Master of Chaos


      Wizard lvl 9


      Human
  socialIcons:
    - name: mastodon
      url: "https://mastodon.social/@__warlord__"
    - name: RSS
      url: "index.xml"

  # Search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
    
  analytics:
    google:
      SiteVerificationTag: "G-ZRB1GGCC9B"

  assets:
    disableHLJS: true
    # Update theme colors to match cyberpunk palette
    theme_color: "#0d0221"
    msapplication_TileColor: "#0d0221"

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
      hardWraps: false
  highlight:
    noClasses: true
    codeFences: true
    guessSyntax: true
    style: solarized-dark
    # anchorLineNos: true
    # lineNos: true

pagination:
  pagerSize: 5000

# Privacy Settings
privacy:
  vimeo:
    disabled: false
    simple: true
    enableDNT: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true
    
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true

# Services
services:
  instagram:
    disableInlineCSS: true
  googleAnalytics:
    ID: "G-ZRB1GGCC9B"

# Sitemap
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

# Image Processing
imaging:
  quality: 85
  resampleFilter: lanczos
  anchor: smart
  bgColor: "#ffffff"
  
# Caching
caches:
  getresource:
    maxAge: 24h
  getjson:
    maxAge: 24h
  getcsv:
    maxAge: 24h
  images:
    maxAge: 720h
  assets:
    maxAge: 720h
    
# Module Configuration (if using Hugo Modules)
module:
  noProxy: "none"
  noVendor: ""
  
# Build Configuration
build:
  writeStats: true
  noJSConfigInAssets: false
  useResourceCacheWhen: fallback

ignoreLogs:
  - "err-youtube-remote"
