baseURL = "https://memogarcia.mx/"
languageCode = "en-us"
title = "Memo Garcia"
theme = "archie"

publishDir = ""

[params]
    author = "Memo Garcia"
    github = "memogarcia"
    gitlab = "memogarcia"
    sitename = "Memo Garcia"