name: Build Writer Tool

on:
  push:
    branches: [master]
    paths:
      - 'static/tools/writer/src/**'
      - 'static/tools/writer/package.json'
      - 'static/tools/writer/package-lock.json'
      - 'static/tools/writer/vite.config.ts'
      - 'static/tools/writer/tsconfig.json'
      - 'static/tools/writer/tailwind.config.js'
      - 'static/tools/writer/postcss.config.js'
  pull_request:
    branches: [master]
    paths:
      - 'static/tools/writer/src/**'
      - 'static/tools/writer/package.json'
      - 'static/tools/writer/package-lock.json'
      - 'static/tools/writer/vite.config.ts'
      - 'static/tools/writer/tsconfig.json'
      - 'static/tools/writer/tailwind.config.js'
      - 'static/tools/writer/postcss.config.js'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-writer:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'static/tools/writer/package-lock.json'

      - name: Install Writer tool dependencies
        working-directory: ./static/tools/writer
        run: npm ci

      - name: Run Writer tool tests (if available)
        working-directory: ./static/tools/writer
        run: npm run test --if-present || true

      - name: Build Writer tool
        working-directory: ./static/tools/writer
        run: npm run build
          
      - name: Update Writer production files
        working-directory: ./static/tools/writer
        run: |
          # Save the development version
          cp index.html index.dev.html
          
          # Remove old assets if they exist
          rm -rf ./assets
          # Copy new built assets
          cp -r dist/assets ./
          
          # Use the built index.html for production
          cp dist/index.html index.html
          
          # Fix asset paths in production index.html to be relative
          sed -i 's|href="/assets/|href="./assets/|g' index.html
          sed -i 's|src="/assets/|src="./assets/|g' index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add static/tools/writer/assets static/tools/writer/index.html static/tools/writer/index.dev.html
          git diff --staged --quiet || (git commit -m "Build Writer tool - Update production assets [skip ci]" && git push)